//go:build ignore
// +build ignore

package main

import (
	"log"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	log.Println("Generating entutils/entgql schema files...")
	graphqlEx, err := entgql.NewExtension(
		entgql.WithConfigPath("gqlgen.yml"),
		entgql.WithSchemaGenerator(),
		entgql.WithSchemaPath("./ent.graphql"),
		entgql.WithWhereInputs(true),
		entgql.WithNodeDescriptor(true),
	)
	if err != nil {
		log.Fatalf("creating entgql extension: %v", err)
	}
	opts := []entc.Option{
		entc.Extensions(graphqlEx),
		entc.FeatureNames("privacy", "intercept"),
	}
	tpls := []*gen.Template{}

	t1 := gen.NewTemplate("i18ndatetime")
	t1.ParseFiles("ent/template/i18ndatetime.tmpl")
	tpls = append(tpls, t1)

	if err := entc.Generate("./ent/schema", &gen.Config{
		Templates: tpls,
		Header: `
			// OHMAB
			// Code generated by entc, DO NOT EDIT.
		`}, opts...); err != nil {
		log.Fatalf("running entutils codegen: %v", err)
	}
}
