// OHMAB
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hkonitzer/ohmab/ent/predicate"
	"github.com/hkonitzer/ohmab/ent/publicuser"
)

// PublicUserDelete is the builder for deleting a PublicUser entity.
type PublicUserDelete struct {
	config
	hooks    []Hook
	mutation *PublicUserMutation
}

// Where appends a list predicates to the PublicUserDelete builder.
func (pud *PublicUserDelete) Where(ps ...predicate.PublicUser) *PublicUserDelete {
	pud.mutation.Where(ps...)
	return pud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pud *PublicUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pud.sqlExec, pud.mutation, pud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pud *PublicUserDelete) ExecX(ctx context.Context) int {
	n, err := pud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pud *PublicUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(publicuser.Table, sqlgraph.NewFieldSpec(publicuser.FieldID, field.TypeUUID))
	if ps := pud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pud.mutation.done = true
	return affected, err
}

// PublicUserDeleteOne is the builder for deleting a single PublicUser entity.
type PublicUserDeleteOne struct {
	pud *PublicUserDelete
}

// Where appends a list predicates to the PublicUserDelete builder.
func (pudo *PublicUserDeleteOne) Where(ps ...predicate.PublicUser) *PublicUserDeleteOne {
	pudo.pud.mutation.Where(ps...)
	return pudo
}

// Exec executes the deletion query.
func (pudo *PublicUserDeleteOne) Exec(ctx context.Context) error {
	n, err := pudo.pud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{publicuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pudo *PublicUserDeleteOne) ExecX(ctx context.Context) {
	if err := pudo.Exec(ctx); err != nil {
		panic(err)
	}
}
