// OHMAB
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hkonitzer/ohmab/ent/publicuser"
)

// PublicUser is the model entity for the PublicUser schema.
type PublicUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The surname of a user
	Surname string `json:"surname,omitempty"`
	// The first name of a user
	Firstname string `json:"firstname,omitempty"`
	// The title of a user like PhD
	Title string `json:"title,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PublicUserQuery when eager-loading is set.
	Edges        PublicUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PublicUserEdges holds the relations/edges for other nodes in the graph.
type PublicUserEdges struct {
	// The businesses this user is associated with
	Businesses []*Business `json:"businesses,omitempty"`
	// The persons on duty for this timetable entry
	Timetable []*Timetable `json:"timetable,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedBusinesses map[string][]*Business
	namedTimetable  map[string][]*Timetable
}

// BusinessesOrErr returns the Businesses value or an error if the edge
// was not loaded in eager-loading.
func (e PublicUserEdges) BusinessesOrErr() ([]*Business, error) {
	if e.loadedTypes[0] {
		return e.Businesses, nil
	}
	return nil, &NotLoadedError{edge: "businesses"}
}

// TimetableOrErr returns the Timetable value or an error if the edge
// was not loaded in eager-loading.
func (e PublicUserEdges) TimetableOrErr() ([]*Timetable, error) {
	if e.loadedTypes[1] {
		return e.Timetable, nil
	}
	return nil, &NotLoadedError{edge: "timetable"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PublicUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case publicuser.FieldSurname, publicuser.FieldFirstname, publicuser.FieldTitle, publicuser.FieldEmail:
			values[i] = new(sql.NullString)
		case publicuser.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PublicUser fields.
func (pu *PublicUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case publicuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pu.ID = *value
			}
		case publicuser.FieldSurname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field surname", values[i])
			} else if value.Valid {
				pu.Surname = value.String
			}
		case publicuser.FieldFirstname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field firstname", values[i])
			} else if value.Valid {
				pu.Firstname = value.String
			}
		case publicuser.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				pu.Title = value.String
			}
		case publicuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				pu.Email = value.String
			}
		default:
			pu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PublicUser.
// This includes values selected through modifiers, order, etc.
func (pu *PublicUser) Value(name string) (ent.Value, error) {
	return pu.selectValues.Get(name)
}

// QueryBusinesses queries the "businesses" edge of the PublicUser entity.
func (pu *PublicUser) QueryBusinesses() *BusinessQuery {
	return NewPublicUserClient(pu.config).QueryBusinesses(pu)
}

// QueryTimetable queries the "timetable" edge of the PublicUser entity.
func (pu *PublicUser) QueryTimetable() *TimetableQuery {
	return NewPublicUserClient(pu.config).QueryTimetable(pu)
}

// Update returns a builder for updating this PublicUser.
// Note that you need to call PublicUser.Unwrap() before calling this method if this PublicUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (pu *PublicUser) Update() *PublicUserUpdateOne {
	return NewPublicUserClient(pu.config).UpdateOne(pu)
}

// Unwrap unwraps the PublicUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pu *PublicUser) Unwrap() *PublicUser {
	_tx, ok := pu.config.driver.(*txDriver)
	if !ok {
		panic("ent: PublicUser is not a transactional entity")
	}
	pu.config.driver = _tx.drv
	return pu
}

// String implements the fmt.Stringer.
func (pu *PublicUser) String() string {
	var builder strings.Builder
	builder.WriteString("PublicUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pu.ID))
	builder.WriteString("surname=")
	builder.WriteString(pu.Surname)
	builder.WriteString(", ")
	builder.WriteString("firstname=")
	builder.WriteString(pu.Firstname)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(pu.Title)
	builder.WriteString(", ")
	builder.WriteString("email=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// NamedBusinesses returns the Businesses named value or an error if the edge was not
// loaded in eager-loading with this name.
func (pu *PublicUser) NamedBusinesses(name string) ([]*Business, error) {
	if pu.Edges.namedBusinesses == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := pu.Edges.namedBusinesses[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (pu *PublicUser) appendNamedBusinesses(name string, edges ...*Business) {
	if pu.Edges.namedBusinesses == nil {
		pu.Edges.namedBusinesses = make(map[string][]*Business)
	}
	if len(edges) == 0 {
		pu.Edges.namedBusinesses[name] = []*Business{}
	} else {
		pu.Edges.namedBusinesses[name] = append(pu.Edges.namedBusinesses[name], edges...)
	}
}

// NamedTimetable returns the Timetable named value or an error if the edge was not
// loaded in eager-loading with this name.
func (pu *PublicUser) NamedTimetable(name string) ([]*Timetable, error) {
	if pu.Edges.namedTimetable == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := pu.Edges.namedTimetable[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (pu *PublicUser) appendNamedTimetable(name string, edges ...*Timetable) {
	if pu.Edges.namedTimetable == nil {
		pu.Edges.namedTimetable = make(map[string][]*Timetable)
	}
	if len(edges) == 0 {
		pu.Edges.namedTimetable[name] = []*Timetable{}
	} else {
		pu.Edges.namedTimetable[name] = append(pu.Edges.namedTimetable[name], edges...)
	}
}

// PublicUsers is a parsable slice of PublicUser.
type PublicUsers []*PublicUser
